// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cinemas.sql

package database

import (
	"context"

	"github.com/geneowak/go-expense-tracker/internal/types"
	"github.com/google/uuid"
)

const createCinema = `-- name: CreateCinema :one
INSERT INTO
    cinemas(
        id,
        name,
        location_id,
        experience_types,
        seat_map,
        created_at,
        updated_at
    )
VALUES
(uuidv7(), $1, $2, $3, $4, NOW(), NOW())
RETURNING
    id, location_id, name, experience_types, seat_map, created_at, updated_at
`

type CreateCinemaParams struct {
	Name            string            `json:"name"`
	LocationID      uuid.UUID         `json:"location_id"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	SeatMap         types.SeatMap     `json:"seat_map"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRowContext(ctx, createCinema,
		arg.Name,
		arg.LocationID,
		arg.ExperienceTypes,
		arg.SeatMap,
	)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.ExperienceTypes,
		&i.SeatMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
