// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cinemas.sql

package database

import (
	"context"

	"github.com/geneowak/go-expense-tracker/internal/types"
	"github.com/google/uuid"
)

const checkCinemaById = `-- name: CheckCinemaById :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            cinemas
        WHERE
            id = $1
    )
`

func (q *Queries) CheckCinemaById(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkCinemaById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCinema = `-- name: CreateCinema :one
INSERT INTO
    cinemas(
        id,
        name,
        location_id,
        experience_types,
        seat_map,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, $4, NOW(), NOW())
RETURNING
    id, location_id, name, experience_types, seat_map, created_at, updated_at
`

type CreateCinemaParams struct {
	Name            string            `json:"name"`
	LocationID      uuid.UUID         `json:"location_id"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	SeatMap         types.SeatMap     `json:"seat_map"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, createCinema,
		arg.Name,
		arg.LocationID,
		arg.ExperienceTypes,
		arg.SeatMap,
	)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.ExperienceTypes,
		&i.SeatMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCinemaDetails = `-- name: UpdateCinemaDetails :one
UPDATE
    cinemas
SET
    name = $1,
    experience_types = $2,
    seat_map = $3
WHERE
    id = $4
RETURNING
    id, location_id, name, experience_types, seat_map, created_at, updated_at
`

type UpdateCinemaDetailsParams struct {
	Name            string            `json:"name"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	SeatMap         types.SeatMap     `json:"seat_map"`
	ID              uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateCinemaDetails(ctx context.Context, arg UpdateCinemaDetailsParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, updateCinemaDetails,
		arg.Name,
		arg.ExperienceTypes,
		arg.SeatMap,
		arg.ID,
	)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.ExperienceTypes,
		&i.SeatMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
