// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_movies.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/geneowak/cinehold/internal/types"
	"github.com/google/uuid"
)

const getAllMovies = `-- name: GetAllMovies :many
SELECT
    movies.id, movies.name, movies.description, movies.duration_in_mins, movies.trailer_url, movies.genre, movies.pg_rating, movies.experience_types, movies.created_at, movies.updated_at, movies.poster_image_url,
    COALESCE(
        (
            SELECT
                jsonb_agg(
                    to_jsonb(st)
                    ORDER BY
                        st.start_date,
                        st.start_time
                )
            FROM
                show_times st
            WHERE
                st.movie_id = movies.id
        ),
        '[]'::jsonb
    ) AS show_times
FROM
    movies
ORDER BY
    (
        SELECT
            min(st.start_date)
        FROM
            show_times st
        WHERE
            st.movie_id = movies.id
    ) ASC
`

type GetAllMoviesRow struct {
	ID              uuid.UUID         `json:"id"`
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DurationInMins  int32             `json:"duration_in_mins"`
	TrailerUrl      string            `json:"trailer_url"`
	Genre           types.StringSlice `json:"genre"`
	PgRating        string            `json:"pg_rating"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	PosterImageUrl  *string           `json:"poster_image_url"`
	ShowTimes       interface{}       `json:"show_times"`
}

func (q *Queries) GetAllMovies(ctx context.Context) ([]GetAllMoviesRow, error) {
	rows, err := q.db.Query(ctx, getAllMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMoviesRow
	for rows.Next() {
		var i GetAllMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationInMins,
			&i.TrailerUrl,
			&i.Genre,
			&i.PgRating,
			&i.ExperienceTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PosterImageUrl,
			&i.ShowTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowingMovies = `-- name: GetShowingMovies :many
WITH filtered_shows AS (
    SELECT
        st.movie_id,
        jsonb_agg(
            to_jsonb(st)
            ORDER BY
                st.start_date,
                st.start_time
        ) AS show_times,
        min(st.start_date) AS first_show_date
    FROM
        show_times st
    WHERE
        st.end_date >= CURRENT_DATE
        AND (
            $2::time IS NULL
            OR st.start_time >= $2
        )
        AND (
            $3::timestamp IS NULL
            OR st.start_date <= $3
        )
    GROUP BY
        st.movie_id
)
SELECT
    movies.id, movies.name, movies.description, movies.duration_in_mins, movies.trailer_url, movies.genre, movies.pg_rating, movies.experience_types, movies.created_at, movies.updated_at, movies.poster_image_url,
    fs.show_times
FROM
    movies
    INNER JOIN filtered_shows fs ON movies.id = fs.movie_id
WHERE
    (
        $1::text IS NULL
        OR movies.genre::jsonb @> jsonb_build_array($1::text)
    )
ORDER BY
    fs.first_show_date ASC
`

type GetShowingMoviesParams struct {
	Genre *string    `json:"genre"`
	Time  *time.Time `json:"time"`
	Date  *time.Time `json:"date"`
}

type GetShowingMoviesRow struct {
	ID              uuid.UUID         `json:"id"`
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DurationInMins  int32             `json:"duration_in_mins"`
	TrailerUrl      string            `json:"trailer_url"`
	Genre           types.StringSlice `json:"genre"`
	PgRating        string            `json:"pg_rating"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	PosterImageUrl  *string           `json:"poster_image_url"`
	ShowTimes       json.RawMessage   `json:"show_times"`
}

func (q *Queries) GetShowingMovies(ctx context.Context, arg GetShowingMoviesParams) ([]GetShowingMoviesRow, error) {
	rows, err := q.db.Query(ctx, getShowingMovies, arg.Genre, arg.Time, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowingMoviesRow
	for rows.Next() {
		var i GetShowingMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationInMins,
			&i.TrailerUrl,
			&i.Genre,
			&i.PgRating,
			&i.ExperienceTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PosterImageUrl,
			&i.ShowTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
