// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package database

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO
    locations(
        id,
        name,
        address,
        google_map_url,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, NOW(), NOW())
RETURNING
    id, name, address, google_map_url, created_at, updated_at
`

type CreateLocationParams struct {
	Name         string `json:"name"`
	Address      string `json:"address"`
	GoogleMapUrl string `json:"google_map_url"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Address, arg.GoogleMapUrl)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.GoogleMapUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocations = `-- name: GetLocations :many
SELECT
    id, name, address, google_map_url, created_at, updated_at
FROM
    locations
`

func (q *Queries) GetLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.GoogleMapUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
