// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO
    locations(
        id,
        name,
        address,
        google_map_url,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, NOW(), NOW())
RETURNING
    id, name, address, google_map_url, created_at, updated_at
`

type CreateLocationParams struct {
	Name         string `json:"name"`
	Address      string `json:"address"`
	GoogleMapUrl string `json:"google_map_url"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Address, arg.GoogleMapUrl)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.GoogleMapUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationDetails = `-- name: GetLocationDetails :one
SELECT
    locations.id, locations.name, locations.address, locations.google_map_url, locations.created_at, locations.updated_at,
    COALESCE(c_agg.venues, '[]'::jsonb) AS cinemas
FROM
    locations
    LEFT JOIN LATERAL(
        SELECT
            jsonb_agg(
                to_jsonb(c)
                ORDER BY
                    c.created_at
            ) AS venues
        FROM
            cinemas c
        WHERE
            c.location_id = locations.id
    ) c_agg ON TRUE
WHERE
    locations.id = $1
`

type GetLocationDetailsRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Address      string    `json:"address"`
	GoogleMapUrl string    `json:"google_map_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Cinemas      []byte    `json:"cinemas"`
}

func (q *Queries) GetLocationDetails(ctx context.Context, id uuid.UUID) (GetLocationDetailsRow, error) {
	row := q.db.QueryRow(ctx, getLocationDetails, id)
	var i GetLocationDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.GoogleMapUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cinemas,
	)
	return i, err
}

const getLocations = `-- name: GetLocations :many
SELECT
    id, name, address, google_map_url, created_at, updated_at
FROM
    locations
`

func (q *Queries) GetLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.GoogleMapUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
