// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package database

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO
    locations(
        id,
        name,
        address,
        google_map_url,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, NOW(), NOW())
RETURNING
    id, name, address, google_map_url, created_at, updated_at
`

type CreateLocationParams struct {
	Name         string `json:"name"`
	Address      string `json:"address"`
	GoogleMapUrl string `json:"google_map_url"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Address, arg.GoogleMapUrl)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.GoogleMapUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
