// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package database

import (
	"context"

	"github.com/geneowak/go-expense-tracker/internal/types"
	"github.com/google/uuid"
)

const checkMovieById = `-- name: CheckMovieById :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            movies
        WHERE
            id = $1
    )
`

func (q *Queries) CheckMovieById(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkMovieById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO
    movies(
        id,
        name,
        description,
        duration_in_mins,
        trailer_url,
        genre,
        pg_rating,
        experience_types,
        created_at,
        updated_at
    )
VALUES
    (
        uuidv7(),
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        NOW(),
        NOW()
    )
RETURNING
    id, name, poster_image_url, description, duration_in_mins, trailer_url, genre, pg_rating, experience_types, created_at, updated_at
`

type CreateMovieParams struct {
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DurationInMins  int32             `json:"duration_in_mins"`
	TrailerUrl      string            `json:"trailer_url"`
	Genre           types.StringSlice `json:"genre"`
	PgRating        string            `json:"pg_rating"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Name,
		arg.Description,
		arg.DurationInMins,
		arg.TrailerUrl,
		arg.Genre,
		arg.PgRating,
		arg.ExperienceTypes,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosterImageUrl,
		&i.Description,
		&i.DurationInMins,
		&i.TrailerUrl,
		&i.Genre,
		&i.PgRating,
		&i.ExperienceTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieById = `-- name: GetMovieById :one
SELECT
    id, name, poster_image_url, description, duration_in_mins, trailer_url, genre, pg_rating, experience_types, created_at, updated_at
FROM
    movies
WHERE
    id = $1
`

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieById, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosterImageUrl,
		&i.Description,
		&i.DurationInMins,
		&i.TrailerUrl,
		&i.Genre,
		&i.PgRating,
		&i.ExperienceTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowingMovies = `-- name: GetShowingMovies :many
SELECT
    movies.id, movies.name, movies.poster_image_url, movies.description, movies.duration_in_mins, movies.trailer_url, movies.genre, movies.pg_rating, movies.experience_types, movies.created_at, movies.updated_at
FROM
    movies
    LEFT JOIN show_times ON show_times.movie_id = movies.id
WHERE
    show_times.start_date >= NOW()
    AND show_times.endtimes <= NOW()
GROUP BY
    movies.id
ORDER BY
    show_times.start_date
`

func (q *Queries) GetShowingMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getShowingMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosterImageUrl,
			&i.Description,
			&i.DurationInMins,
			&i.TrailerUrl,
			&i.Genre,
			&i.PgRating,
			&i.ExperienceTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
