// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package database

import (
	"context"
	"time"

	"github.com/geneowak/go-expense-tracker/internal/types"
	"github.com/google/uuid"
)

const checkMovieById = `-- name: CheckMovieById :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            movies
        WHERE
            id = $1
    )
`

func (q *Queries) CheckMovieById(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkMovieById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO
    movies(
        id,
        name,
        description,
        duration_in_mins,
        trailer_url,
        genre,
        pg_rating,
        experience_types,
        created_at,
        updated_at
    )
VALUES
    (
        uuidv7(),
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        NOW(),
        NOW()
    )
RETURNING
    id, name, description, duration_in_mins, trailer_url, genre, pg_rating, experience_types, created_at, updated_at, poster_image_url
`

type CreateMovieParams struct {
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DurationInMins  int32             `json:"duration_in_mins"`
	TrailerUrl      string            `json:"trailer_url"`
	Genre           types.StringSlice `json:"genre"`
	PgRating        string            `json:"pg_rating"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Name,
		arg.Description,
		arg.DurationInMins,
		arg.TrailerUrl,
		arg.Genre,
		arg.PgRating,
		arg.ExperienceTypes,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationInMins,
		&i.TrailerUrl,
		&i.Genre,
		&i.PgRating,
		&i.ExperienceTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageUrl,
	)
	return i, err
}

const getMovieById = `-- name: GetMovieById :one
SELECT
    id, name, description, duration_in_mins, trailer_url, genre, pg_rating, experience_types, created_at, updated_at, poster_image_url
FROM
    movies
WHERE
    id = $1
`

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieById, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationInMins,
		&i.TrailerUrl,
		&i.Genre,
		&i.PgRating,
		&i.ExperienceTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageUrl,
	)
	return i, err
}

const getMovieDetails = `-- name: GetMovieDetails :one
SELECT
    movies.id, movies.name, movies.description, movies.duration_in_mins, movies.trailer_url, movies.genre, movies.pg_rating, movies.experience_types, movies.created_at, movies.updated_at, movies.poster_image_url,
    COALESCE(
        (
            SELECT
                jsonb_agg(
                    to_jsonb(st)
                    ORDER BY
                        st.start_date,
                        st.start_time
                )
            FROM
                show_times st
            WHERE
                st.movie_id = movies.id
        ),
        '[]'::jsonb
    ) AS show_times
FROM
    movies
WHERE
    movies.id = $1
`

type GetMovieDetailsRow struct {
	ID              uuid.UUID         `json:"id"`
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DurationInMins  int32             `json:"duration_in_mins"`
	TrailerUrl      string            `json:"trailer_url"`
	Genre           types.StringSlice `json:"genre"`
	PgRating        string            `json:"pg_rating"`
	ExperienceTypes types.StringSlice `json:"experience_types"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	PosterImageUrl  *string           `json:"poster_image_url"`
	ShowTimes       interface{}       `json:"show_times"`
}

func (q *Queries) GetMovieDetails(ctx context.Context, id uuid.UUID) (GetMovieDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMovieDetails, id)
	var i GetMovieDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationInMins,
		&i.TrailerUrl,
		&i.Genre,
		&i.PgRating,
		&i.ExperienceTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageUrl,
		&i.ShowTimes,
	)
	return i, err
}
