// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckCinemaById(ctx context.Context, id uuid.UUID) (bool, error)
	CheckMovieById(ctx context.Context, id uuid.UUID) (bool, error)
	CheckUserId(ctx context.Context, id uuid.UUID) (bool, error)
	CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (ShowTime, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	RevokeRefreshToken(ctx context.Context, token string) error
}

var _ Querier = (*Queries)(nil)
