// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckCinemaById(ctx context.Context, id uuid.UUID) (bool, error)
	CheckMovieById(ctx context.Context, id uuid.UUID) (bool, error)
	CheckUserId(ctx context.Context, id uuid.UUID) (bool, error)
	CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (ShowTime, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserBooking(ctx context.Context, arg DeleteUserBookingParams) error
	GetAllMovies(ctx context.Context) ([]GetAllMoviesRow, error)
	GetLocationDetails(ctx context.Context, id uuid.UUID) (GetLocationDetailsRow, error)
	GetLocations(ctx context.Context) ([]Location, error)
	GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error)
	GetMovieDetails(ctx context.Context, id uuid.UUID) (GetMovieDetailsRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetReservationBySeatNo(ctx context.Context, arg GetReservationBySeatNoParams) (Reservation, error)
	GetShowTimeDetails(ctx context.Context, id uuid.UUID) (GetShowTimeDetailsRow, error)
	GetShowTimeReservations(ctx context.Context, arg GetShowTimeReservationsParams) ([]Reservation, error)
	GetShowingMovies(ctx context.Context, arg GetShowingMoviesParams) ([]GetShowingMoviesRow, error)
	GetUserBookingById(ctx context.Context, arg GetUserBookingByIdParams) (Reservation, error)
	GetUserBookings(ctx context.Context, userID uuid.UUID) ([]Reservation, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	MarkReservationBooked(ctx context.Context, arg MarkReservationBookedParams) (Reservation, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error)
}

var _ Querier = (*Queries)(nil)
