// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO
    reservations(
        id,
        show_time_id,
        user_id,
        seat_no,
        reserved_at,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, NOW(), NOW(), NOW())
RETURNING
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
`

type CreateReservationParams struct {
	ShowTimeID uuid.UUID `json:"show_time_id"`
	UserID     uuid.UUID `json:"user_id"`
	SeatNo     string    `json:"seat_no"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation, arg.ShowTimeID, arg.UserID, arg.SeatNo)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
