// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO
    reservations(
        id,
        user_id,
        seat_no,
        show_time_id,
        reserved_at,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, NOW(), NOW(), NOW())
RETURNING
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
`

type CreateReservationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	SeatNo     string    `json:"seat_no"`
	ShowTimeID uuid.UUID `json:"show_time_id"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation, arg.UserID, arg.SeatNo, arg.ShowTimeID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserBooking = `-- name: DeleteUserBooking :exec
DELETE FROM
    reservations
WHERE
    id = $1
    AND user_id = $2
`

type DeleteUserBookingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserBooking(ctx context.Context, arg DeleteUserBookingParams) error {
	_, err := q.db.Exec(ctx, deleteUserBooking, arg.ID, arg.UserID)
	return err
}

const getReservationBySeatNo = `-- name: GetReservationBySeatNo :one
SELECT
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
FROM
    reservations
WHERE
    show_time_id = $1
    AND seat_no = $2
LIMIT
    1
`

type GetReservationBySeatNoParams struct {
	ShowTimeID uuid.UUID `json:"show_time_id"`
	SeatNo     string    `json:"seat_no"`
}

func (q *Queries) GetReservationBySeatNo(ctx context.Context, arg GetReservationBySeatNoParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationBySeatNo, arg.ShowTimeID, arg.SeatNo)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBookingById = `-- name: GetUserBookingById :one
SELECT
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
FROM
    reservations
WHERE
    STATUS = 'booked'
    AND id = $1
    AND user_id = $2
LIMIT
    1
`

type GetUserBookingByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserBookingById(ctx context.Context, arg GetUserBookingByIdParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getUserBookingById, arg.ID, arg.UserID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBookings = `-- name: GetUserBookings :many
SELECT
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
FROM
    reservations
WHERE
    STATUS = 'booked'
    AND user_id = $1
`

func (q *Queries) GetUserBookings(ctx context.Context, userID uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getUserBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ShowTimeID,
			&i.UserID,
			&i.SeatNo,
			&i.Status,
			&i.ReservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservationBooked = `-- name: MarkReservationBooked :one
UPDATE
    reservations
SET
    STATUS = 'booked',
    reserved_at = NULL
WHERE
    id = $1
    AND user_id = $2
RETURNING
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
`

type MarkReservationBookedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkReservationBooked(ctx context.Context, arg MarkReservationBookedParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, markReservationBooked, arg.ID, arg.UserID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservation = `-- name: UpdateReservation :one
UPDATE
    reservations
SET
    user_id = $1,
    reserved_at = NOW()
WHERE
    seat_no = $2
    AND show_time_id = $3
RETURNING
    id, show_time_id, user_id, seat_no, status, reserved_at, created_at, updated_at
`

type UpdateReservationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	SeatNo     string    `json:"seat_no"`
	ShowTimeID uuid.UUID `json:"show_time_id"`
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservation, arg.UserID, arg.SeatNo, arg.ShowTimeID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ShowTimeID,
		&i.UserID,
		&i.SeatNo,
		&i.Status,
		&i.ReservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
