// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: show_times.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createShowTime = `-- name: CreateShowTime :one
INSERT INTO
    show_times(
        id,
        start_time,
        price,
        movie_id,
        cinema_id,
        experience_type,
        start_date,
        end_date,
        created_at,
        updated_at
    )
VALUES
    (
        uuidv7(),
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        NOW(),
        NOW()
    )
RETURNING
    id, start_time, price, description, price_currency, movie_id, cinema_id, experience_type, start_date, end_date, created_at, updated_at
`

type CreateShowTimeParams struct {
	StartTime      time.Time `json:"start_time"`
	Price          int32     `json:"price"`
	MovieID        uuid.UUID `json:"movie_id"`
	CinemaID       uuid.UUID `json:"cinema_id"`
	ExperienceType string    `json:"experience_type"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}

func (q *Queries) CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (ShowTime, error) {
	row := q.db.QueryRowContext(ctx, createShowTime,
		arg.StartTime,
		arg.Price,
		arg.MovieID,
		arg.CinemaID,
		arg.ExperienceType,
		arg.StartDate,
		arg.EndDate,
	)
	var i ShowTime
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.Price,
		&i.Description,
		&i.PriceCurrency,
		&i.MovieID,
		&i.CinemaID,
		&i.ExperienceType,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
